name = "Flows"
authors = ["Davide Lasagna <davide.lasagna@soton.ac.uk>"]
version = "0.0.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
